### ISSUE TITLE
InvalidArgumentException The filename and the fallback cannot contain the "/" and "\" characters.

### ISSUE THREAD

**Issue by marcusand** [Roorda-ICT/statamic-entries-export#2]
Hi there,

thanks for the plugin!
Unfortunately I have some problems with it. On some collections I get an 

``` 
InvalidArgumentException
The filename and the fallback cannot contain the "/" and "\" characters.
```` 

error.
Running on
````
Statamic 3.1.26 Pro
Laravel 8.80.0
PHP 8.0.15
roorda-ict/statamic-entries-export 1.0.0
```` 

Any ideas?

Full stack trace 

````
3470669 [2022-07-14 13:23:34] local.ERROR: The filename and the fallback cannot contain the "/" and "\" characters. {"userId":"f34a82ae-5501-4519-9e18-418131f2be95","exception":"[object] (InvalidArgumentException(code: 0): The filename and the fallback cannot contain the \"/\" and \"\\\" characters. at /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/symfony/http-foundation/HeaderUtils.        php:183)
3470670 [stacktrace]
3470671 #0 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/symfony/http-foundation/ResponseHeaderBag.php(252): Symfony\\Component\\HttpFoundation\\HeaderUtils::makeDisposition('attachment', 'Landkarte/Reche...', 'Landkarte/Reche...')
3470672 #1 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/symfony/http-foundation/BinaryFileResponse.php(181): Symfony\\Component\\HttpFoundation\\ResponseHeaderBag->makeDisposition('attachment', 'Landkarte/Reche...', 'Landkarte/Reche...')
3470673 #2 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(168): Symfony\\Component\\HttpFoundation\\BinaryFileResponse->setContentDisposition('attachment', 'Landkarte/Reche...', 'Landkarte/Reche...')
3470674 #3 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/maatwebsite/excel/src/Excel.php(84): Illuminate\\Routing\\ResponseFactory->download('/Users/marcus/p...', 'Landkarte/Reche...', Array)
3470675 #4 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/maatwebsite/excel/src/Concerns/Exportable.php(30): Maatwebsite\\Excel\\Excel->download(Object(RoordaIct\\EntriesExport\\Exports\\EntryCollectionExport), 'Landkarte/Reche...', NULL, Array)
3470676 #5 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/roorda-ict/statamic-entries-export/src/Http/Controllers/ExportController.php(48): RoordaIct\\EntriesExport\\Exports\\EntryCollectionExport->download('Landkarte/Reche...')
3470677 #6 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): RoordaIct\\EntriesExport\\Http\\Controllers\\ExportController->download(Object(Illuminate\\Http\\Request))
3470678 #7 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(RoordaIct\\EntriesExport\\Http\\Controllers\\ExportController), 'download')
3470679 #8 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
3470680 #9 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
3470681 #10 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
3470682 #11 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470683 #12 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470684 #13 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470685 #14 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470686 #15 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470687 #16 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470688 #17 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470689 #18 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470690 #19 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470691 #20 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470692 #21 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470693 #22 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470694 #23 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470695 #24 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470696 #25 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470697 #26 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470698 #27 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470699 #28 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
3470700 #29 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470701 #30 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470702 #31 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470703 #32 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470704 #33 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470705 #34 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470706 #35 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470707 #36 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470708 #37 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
3470709 #38 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
3470710 #39 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
3470711 #40 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
3470712 #41 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
3470713 #42 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
3470714 #43 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470715 #44 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470716 #45 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470717 #46 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470718 #47 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470719 #48 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470720 #49 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470721 #50 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470722 #51 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470723 #52 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470724 #53 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470725 #54 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470726 #55 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470727 #56 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470728 #57 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470729 #58 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470730 #59 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470731 #60 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470732 #61 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470733 #62 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470734 #63 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470735 #64 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470736 #65 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470737 #66 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3470738 #67 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3470739 #68 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
3470740 #69 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
3470741 #70 /Users/marcus/projects/arbeit/meso/drm/statamic-v3/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
3470742 #71 /Users/marcus/.composer/vendor/laravel/valet/server.php(234): require('/Users/marcus/p...')
3470743 #72 {main}
3470744 "}
````

**Comment by jelleroorda** [comment]
Hi Marcus, you haven't customized anything right? A quick look suggests that the problem may be that your collection contains a `/` character in it's title, is that correct?

**Comment by marcusand** [comment]
@jelleroorda sorry for the late response.

yeah...that's the issue. Renaming them solved it. 
Not sure why I didn't saw that, sorry for stealing your time :)
